output "address" {
  description = "Forwarding rule addresses."
  value = {
    for k, v in google_compute_global_forwarding_rule.default :
    k => v.ip_address
  }
}

output "backend_service_generated_ids" {
  description = "Generated Ids for backend service resources."
  value = {
    for k, v in google_compute_backend_service.default : k => v.generated_id
  }
}

output "backend_service_ids" {
  description = "Backend service resources."
  value = {
    for k, v in google_compute_backend_service.default : k => v.id
  }
}

output "backend_service_names" {
  description = "Backend service resource names."
  value = {
    for k, v in google_compute_backend_service.default : k => v.name
  }
}

output "forwarding_rules" {
  description = "Forwarding rule resource."
  value       = google_compute_global_forwarding_rule.default
}

output "global_neg_ids" {
  description = "Autogenerated global network endpoint group ids."
  value = {
    for k, v in google_compute_global_network_endpoint_group.default : k => v.id
  }
}

output "group_ids" {
  description = "Autogenerated instance group ids."
  value = {
    for k, v in google_compute_instance_group.default : k => v.id
  }
}

output "health_check_ids" {
  description = "Autogenerated health check ids."
  value = {
    for k, v in google_compute_health_check.default : k => v.id
  }
}

output "ids" {
  description = "Fully qualified forwarding rule ids."
  value = {
    for k, v in google_compute_global_forwarding_rule.default : k => v.id
  }
}

output "neg_ids" {
  description = "Autogenerated network endpoint group ids."
  value = {
    for k, v in google_compute_network_endpoint_group.default : k => v.id
  }
}

output "psc_neg_ids" {
  description = "Autogenerated PSC network endpoint group ids."
  value = {
    for k, v in google_compute_region_network_endpoint_group.psc : k => v.id
  }
}

output "serverless_neg_ids" {
  description = "Autogenerated serverless network endpoint group ids."
  value = {
    for k, v in google_compute_region_network_endpoint_group.serverless : k => v.id
  }
}
